# Generated by Django 5.0.6 on 2024-08-17 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementhistory',
            name='implement_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='live_tracking_data.implement'),
        ),
        migrations.AlterField(
            model_name='live_tracking_data',
            name='fuel_frequency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hub_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('hub_location', models.CharField(choices=[('Kisumu', 'Kisumu'), ('Nakuru', 'Nakuru'), ('Nairobi', 'Nairobi')], default='Kisumu', max_length=100)),
                ('hub_device_imei', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hubs', to='live_tracking_data.device')),
            ],
        ),
        migrations.CreateModel(
            name='HubImplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('attached_beacon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hub_implement', to='live_tracking_data.beacon')),
                ('hub_implement_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_history', to='live_tracking_data.implement')),
                ('hub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_implements', to='live_tracking_data.hub')),
            ],
        ),
    ]
