# Generated by Django 5.0.6 on 2024-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0002_alter_implementhistory_implement_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_tracking_data',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
