# Generated by Django 5.0.6 on 2024-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0002_rename_timestamp_live_tracking_data_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_tracking_data',
            name='asset_battery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live_tracking_data',
            name='engine_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='live_tracking_data',
            name='position',
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AddField(
            model_name='live_tracking_data',
            name='raw_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='live_tracking_data',
            name='sim_iccid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
