# Generated by Django 5.0.6 on 2024-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0003_live_tracking_data_asset_battery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_tracking_data',
            name='iccid1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='live_tracking_data',
            name='iccid2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
