# Generated by Django 5.0.6 on 2024-08-19 23:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0003_alter_live_tracking_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCalibrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_in_litre', models.FloatField()),
                ('raw_fuel_value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_results', to='live_tracking_data.device')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeFuelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_time_fuel_values', to='live_tracking_data.device')),
            ],
        ),
    ]
