# Generated by Django 5.0.6 on 2024-08-21 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0004_fuelcalibrationresult_realtimefuelvalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubimplement',
            options={'verbose_name': 'Hub Implement', 'verbose_name_plural': 'Hub Implements'},
        ),
        migrations.RenameField(
            model_name='hubimplement',
            old_name='hub_name',
            new_name='hub',
        ),
        migrations.RemoveField(
            model_name='hubimplement',
            name='attached_beacon',
        ),
        migrations.RemoveField(
            model_name='hubimplement',
            name='hub_implement_serial',
        ),
        migrations.RemoveField(
            model_name='hubimplement',
            name='implement_type',
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='attached_beacon_id',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_tracking_data.beacon'),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='brand',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_tracking_data.implementbrand'),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='color',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='implement',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hub_implement', to='live_tracking_data.implement'),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='is_within_hub',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='location',
            field=models.CharField(choices=[('KE', 'Kenya'), ('RW', 'Rwanda'), ('UG', 'Uganda'), ('NG', 'Nigeria'), ('ET', 'Ethiopia'), ('TZ', 'Tanzania')], default='Nairobi', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='model',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='hubimplement',
            name='serial_number',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='implement',
            name='associated_with_hub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='implement',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_implements', to='live_tracking_data.hub'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hub',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='implement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='live_tracking_data',
            name='device_id',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='newdevice',
            name='device_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
