# Generated by Django 5.0.6 on 2024-06-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0005_remove_live_tracking_data_iccid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_tracking_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
