# Generated by Django 5.0.6 on 2024-08-21 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0006_alter_implement_created_at_alter_implement_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubimplement',
            name='brand',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='live_tracking_data.implementbrand'),
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='color',
            field=models.CharField(default='UNKNOWN_COLOR', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='location',
            field=models.CharField(choices=[('KE', 'Kenya'), ('RW', 'Rwanda'), ('UG', 'Uganda'), ('NG', 'Nigeria'), ('ET', 'Ethiopia'), ('TZ', 'Tanzania')], default='UNKNOWN_LOCATION', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='model',
            field=models.CharField(default='UNKNOWN_MODEL', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='serial_number',
            field=models.CharField(default='UNKNOWN_SERIAL', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='implement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
