# Generated by Django 5.0.6 on 2024-06-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0006_alter_live_tracking_data_id'),
        ('live_tracking_data', '0007_auto_add_periodic_task'),
    ]

    operations = [
    ]
