# Generated by Django 5.0.6 on 2024-08-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0007_alter_hubimplement_brand_alter_hubimplement_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubimplement',
            name='implement',
        ),
        migrations.AlterField(
            model_name='hubimplement',
            name='hub',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hub_implements', to='live_tracking_data.hub'),
        ),
    ]
