# Generated by Django 5.0.6 on 2024-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0008_merge_20240616_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_tracking_data',
            name='fuel_frequency',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
