# Generated by Django 5.0.6 on 2024-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0009_live_tracking_data_fuel_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField()),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='live_tracking_data',
            name='sim_iccid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
