# Generated by Django 5.0.6 on 2024-07-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0011_device_attributes_device_contact_device_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
