# Generated by Django 5.0.6 on 2024-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0012_alter_device_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
