# Generated by Django 5.0.6 on 2024-07-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0014_alter_device_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='unique_id',
            new_name='device_imei',
        ),
    ]
