# Generated by Django 5.0.6 on 2024-08-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0017_beacon_implement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='namespace_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='implement',
            name='location',
            field=models.CharField(choices=[('KE', 'Kenya'), ('RW', 'Rwanda'), ('UG', 'Uganda'), ('NG', 'Nigeria'), ('ET', 'Ethiopia'), ('TZ', 'Tanzania')], default='KE', max_length=100),
        ),
    ]
