# Generated by Django 5.0.6 on 2024-08-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0018_alter_beacon_namespace_id_alter_implement_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement',
            name='id',
        ),
        migrations.AddField(
            model_name='implement',
            name='serial_number',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
