# Generated by Django 5.0.6 on 2024-08-06 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0020_implement_attached_beacon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detached_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_tracking_data.beacon')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='live_tracking_data.device')),
            ],
        ),
    ]
