# Generated by Django 5.0.6 on 2024-08-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0021_beaconhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beaconhistory',
            name='attached_at',
        ),
        migrations.RemoveField(
            model_name='beaconhistory',
            name='detached_at',
        ),
        migrations.RemoveField(
            model_name='beaconhistory',
            name='duration',
        ),
        migrations.AddField(
            model_name='beaconhistory',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beaconhistory',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='beaconhistory',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='live_tracking_data.beacon'),
        ),
    ]
