# Generated by Django 5.0.6 on 2024-08-07 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0023_remove_beaconhistory_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='implement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
