# Generated by Django 5.0.6 on 2024-08-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0024_beacon_created_at_implement_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeaconHistory',
            new_name='ImplementHistory',
        ),
    ]
