# Generated by Django 5.0.6 on 2024-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0025_rename_beaconhistory_implementhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='active_beacon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='active_implement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
