# Generated by Django 5.0.6 on 2024-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0026_device_active_beacon_device_active_implement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='instance_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='namespace_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='active_beacon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='active_implement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
