# Generated by Django 5.0.6 on 2024-08-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0027_alter_beacon_instance_id_alter_beacon_namespace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='attached_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='attached_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='implement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='implementhistory',
            name='beacon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_tracking_data.beacon'),
        ),
        migrations.AlterField(
            model_name='implementhistory',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
