# Generated by Django 5.0.6 on 2024-08-08 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0028_alter_beacon_attached_time_alter_beacon_attached_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='beacon_rssi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
