# Generated by Django 5.0.6 on 2024-08-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0029_alter_beacon_beacon_rssi_alter_beacon_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='implement',
        ),
        migrations.AlterField(
            model_name='implement',
            name='attached_beacon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implements', to='live_tracking_data.beacon', unique=True),
        ),
    ]
