# Generated by Django 5.0.6 on 2024-08-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracking_data', '0030_remove_beacon_implement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implement',
            name='attached_beacon_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implement', to='live_tracking_data.beacon'),
        ),
    ]
