# Generated by Django 5.0.6 on 2024-06-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_ownershiphistory_ownership_history'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer Details',
        ),
        migrations.AlterModelTable(
            name='implements',
            table='Implement Details',
        ),
        migrations.AlterModelTable(
            name='ownership_history',
            table='Ownership History',
        ),
        migrations.AlterModelTable(
            name='tractor_brand',
            table='Tractor Brands',
        ),
        migrations.AlterModelTable(
            name='tractor_details',
            table='Tractor Details',
        ),
        migrations.AlterModelTable(
            name='tractor_model',
            table='Tractor Models',
        ),
    ]
