# Generated by Django 5.0.6 on 2024-06-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_live_tracking_data_customer_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='live_tracking_data',
        ),
    ]
